#+TITLE:  LaTeX Templates
#+AUTHOR: Xavier Garrido
#+OPTIONS: toc:nil
#+
* Introduction
This file should provide a saner set of LaTeX templates for articles, memos or
beamer templates. It uses all the versatility of =org-mode= from Emacs,
especially all the tangling power of =org-babel=.

The document firstly introduces some general options for LaTeX to work with
=org-mode= and =xelatex=. The second part defines some /chapter/ styles.

Most of the code come from [[https://github.com/kjhealy/latex-custom-kjh][Kieran Healy's LaTeX custom files]].

* Org preamble
:PROPERTIES:
:CUSTOM_ID: org_preamble
:TANGLE: org-preamble.sty
:END:

This section defines =org= preamble and settings for documents exported from
=.org= to =.tex= files. The basic use is to add =\usepackage{org-preamble.sty}=
in your LaTeX document.

** Basics
#+BEGIN_SRC latex
  \NeedsTeXFormat{LaTeX2e}
  \ProvidesPackage{org-preamble}[2013/03/03 v0.01 Bundling of Preamble items for Org to XeLaTeX export]
#+END_SRC

** Style options
Options can be passed to =org-preamble= style file within =\usepackage[options]=
call. For the time being, I have only copied/pasted how to declare such options
but do not use it.
#+BEGIN_SRC latex :tangle no
  \RequirePackage{ifthen}
  \newboolean{@fr} %
  \setboolean{@fr}{false} %
  \DeclareOption{fr}{
    \setboolean{@fr}{true}
  }
  \ProcessOptions
#+END_SRC

** Packages requirements
*** Hyperref settings
#+BEGIN_SRC latex
  \RequirePackage[
    xetex,
    colorlinks=true,
    urlcolor=DarkSlateBlue,
    citecolor=DarkSlateBlue,
    filecolor=DarkSlateBlue,
    plainpages=false,
    pdfpagelabels,
    bookmarksnumbered]{hyperref}
  \RequirePackage{fontspec}
  \RequirePackage{xunicode}
  \RequirePackage{minted}
#+END_SRC

* Article styles
:PROPERTIES:
:CUSTOM_ID: article_styles
:TANGLE: memoir-article-styles.sty
:END:
Some article styles and page layout tweaks for the [[http://www.ctan.org/tex-archive/macros/latex/contrib/memoir/][memoir]] LaTeX class.

** Blank footnote
This piece of code is pretty useful for adding a /blank/ footnote to be used for
corresponding author reference... Use =\symbolfoonote[0]{Footnote text}=.
#+BEGIN_SRC latex
  \long\def\symbolfootnote[#1]#2{%
    \begingroup%
    \def\thefootnote{\fnsymbol{footnote}}\footnote[#1]{#2}%
    \endgroup}
#+END_SRC

** Test chapter style
#+BEGIN_SRC latex
  \makechapterstyle{article-4-sans}{
   \setsecheadstyle{\sffamily\bfseries}
   \setsubsecheadstyle{\normalsize\sffamily\itshape}
       \setaftersubsubsecskip{-1em}
   \setsubsubsecheadstyle{\small}
   \renewcommand{\printchaptername}{}
   \renewcommand{\chapternamenum}{}
   \renewcommand{\chapnumfont}{\chaptitlefont}
   \renewcommand{\printchapternum}{\chapnumfont \thechapter\space}
   \renewcommand{\afterchapternum}{}
   \renewcommand{\printchaptername}{\secheadstyle}
   \renewcommand{\cftchapterfont}{\normalfont}
   \renewcommand{\cftchapterpagefont}{\normalfont\sffamily}
   \renewcommand{\cftchapterpresnum}{\sffamily}
   %\renewcommand{\cftchapterleader}{}
   %\renewcommand{\cftchapterafterpnum}{\cftparfillskip}
   \captiontitlefont{\small}
   %\settocdepth{chapter}
   \maxsecnumdepth{chapter}
   \setsecnumdepth{chapter}

   %% reduce skip after section heading
   \setaftersecskip{1.7ex}

   %% set name of bibliography to 'references'
   %%\renewcommand{\bibname}{\mdseries\Large\sffamily References}

   % % Title flush left
   \pretitle{\par\vskip 3em
       \begin{flushleft}\LARGE\sffamily\bfseries}
   \posttitle{\end{flushleft}\par\vskip 0.5em}
   \preauthor{\begin{flushleft}\Large}
   \postauthor{\end{flushleft}}
   \predate{\begin{flushleft}\normalsize}
   \postdate{\end{flushleft}}

   %% 'abstract' bigger skip from title
   \addto\captionsamerican{\renewcommand*{\abstractname}{}}
   \renewcommand{\abstractnamefont}{\normalfont\scriptsize}
   \renewcommand{\abstracttextfont}{\normalfont\scriptsize}
   \abstractrunin
  }
#+END_SRC
* Exporting styles
:PROPERTIES:
:CUSTOM_ID: export_styles
:TANGLE: latex-templates.sh
:END:
Given the generation of LaTeX styles from the previous items, the files are
exported to =$TEXMFHOME= to make them available from everywhere.

** List of file to export
#+TBLNAME: style_files
| org-preamble.sty          |
| memoir-article-styles.sty |

** Script to do the export
#+NAME: export_script(files=style_files)
#+BEGIN_SRC sh :shebang #!/bin/bash
  if [ ! -d $TEXMFHOME ]; then
      echo "ERROR: No TEXMFHOME installation !"
      return 1
  fi

  latex_dir=$TEXMFHOME/tex/latex/commonstuff
  mode="install"

  if [ "$1" == "clean" ]; then
      mode="clean"
  else
      mkdir -p ${latex_dir}
  fi

  for f in $files
  do
      if [ $mode = install ]; then
          echo "NOTICE: Installing $f into ${latex_dir}"
          cp $f ${latex_dir}/.
      elif [ $mode = clean ]; then
          echo "NOTICE: Removing $f from ${latex_dir}"
          rm -f ${latex_dir}/$f
      fi
  done
#+END_SRC
