#+TITLE:  LaTeX Templates
#+AUTHOR: Xavier Garrido
#+OPTIONS: toc:nil

* Introduction
This file should provide a saner set of LaTeX templates for articles, memos or
beamer templates. It uses all the versatility of =org-mode= from Emacs,
especially all the tangling power of =org-babel=.

The document firstly introduces some general options for LaTeX to work with
=org-mode= and =xelatex=. The second part defines some /chapter/ styles.

Most of the code come from [[https://github.com/kjhealy/latex-custom-kjh][Kieran Healy's LaTeX custom files]].

* Org preamble
:PROPERTIES:
:CUSTOM_ID: org_preamble
:TANGLE:   org-preamble.sty
:END:

This section defines =org= preamble and settings for documents exported from
=.org= to =.tex= files. The basic use is to add =\usepackage{org-preamble}= in
your LaTeX document.

** Basics
#+BEGIN_SRC latex
  \NeedsTeXFormat{LaTeX2e}
  \ProvidesPackage{org-preamble}[2013/03/03 v0.01 Bundling of Preamble items for Org to LaTeX export]
#+END_SRC

** Style options
Options can be passed to =org-preamble= style file within =\usepackage[options]=
call. For the time being, I have only copied/pasted how to declare such options
but do not use it.
#+BEGIN_SRC latex :tangle no
  \RequirePackage{ifthen}
  \newboolean{@fr} %
  \setboolean{@fr}{false} %
  \DeclareOption{fr}{
    \setboolean{@fr}{true}
  }
  \ProcessOptions
#+END_SRC

** Packages requirements
*** AMS packages
#+BEGIN_SRC latex
  \RequirePackage{amsmath}
#+END_SRC
*** Listings package
[[https://code.google.com/p/minted/][minted]] is a package that facilitates expressive syntax highlighting in LaTeX
using the powerful Pygments library. The package also provides options to
customize the highlighted source code output using =fancyvrb=.
#+BEGIN_SRC latex
  \RequirePackage{minted}
#+END_SRC

*** Hyperref settings
#+BEGIN_SRC latex
  %%\RequirePackage[
  %%  backref,
  %%  pagebackref,
  %%  naturalnames=true,
  %%  colorlinks=true,
  %%  plainpages=false,
  %%  pdfpagelabels,
  %%  bookmarksnumbered]{hyperref}
  %%\hypersetup{
  %%  backref,
  %%  pagebackref,
  %%  naturalnames=true,
  %%  colorlinks=true,
  %%  plainpages=false,
  %%  pdfpagelabels,
  %%  bookmarksnumbered}
#+END_SRC
*** Unicode typesettings aka XeTeX
#+BEGIN_SRC latex
  \RequirePackage{ifxetex}
  \ifxetex
  \RequirePackage{fontspec}
  \RequirePackage{xunicode}
  %%\else
  \fi
#+END_SRC

*** [[http://www.ctan.org/pkg/pifont][pifont]] package
#+BEGIN_SRC latex
  \RequirePackage{pifont}
#+END_SRC
* Memoir article styles :DEVELOPMENT:
:PROPERTIES:
:CUSTOM_ID: memoir_article_style
:TANGLE: memoir-article-style.sty
:END:

Some article styles and page layout tweaks for the [[http://www.ctan.org/tex-archive/macros/latex/contrib/memoir/][memoir]] LaTeX class.

** Blank footnote
This piece of code is pretty useful for adding a /blank/ footnote to be used for
corresponding author reference... Use =\symbolfoonote[0]{Footnote text}=.
#+BEGIN_SRC latex
  \long\def\symbolfootnote[#1]#2{%
    \begingroup%
    \def\thefootnote{\fnsymbol{footnote}}\footnote[#1]{#2}%
    \endgroup}
#+END_SRC

** Set font
#+BEGIN_SRC latex
  \setsansfont[Mapping=tex-text]{Myriad Pro}
  \setmonofont[Mapping=tex-text,Scale=MatchLowercase]{Inconsolata}
  \setromanfont[Mapping=tex-text, Numbers=OldStyle]{Minion Pro}
#+END_SRC
** Smaller table font size
#+BEGIN_SRC latex :tangle no
  \usepackage{floatrow}
  \DeclareFloatFont{tiny}{\tiny}% "scriptsize" is defined by floatrow, "tiny" not
  \floatsetup[table]{font=tiny}
#+END_SRC

** Chapter style
#+BEGIN_SRC latex
  \makechapterstyle{article-sans}{
    \setsecheadstyle{\sffamily\bfseries}
    \setsubsecheadstyle{\normalsize\sffamily\itshape}
    \setaftersubsubsecskip{-1em}
    \setsubsubsecheadstyle{\small}
    \renewcommand{\contentsname}{}
    \renewcommand{\printchaptername}{}
    \renewcommand{\chapternamenum}{}
    \renewcommand{\chapnumfont}{\chaptitlefont}
    \renewcommand{\printchapternum}{\chapnumfont \thechapter\space}
    \renewcommand{\afterchapternum}{}
    \renewcommand{\printchaptername}{\secheadstyle}
    \renewcommand{\cftchapterfont}{\normalfont\sffamily}
    \renewcommand{\cftchapterpagefont}{\normalfont\sffamily}
    \renewcommand{\cftchapterpresnum}{\sffamily}
    %\renewcommand{\cftchapterleader}{}
    %\renewcommand{\cftchapterafterpnum}{\cftparfillskip}
    \captiontitlefont{\small}
    %\settocdepth{chapter}
    \maxsecnumdepth{chapter}
    \setsecnumdepth{chapter}

    %% reduce skip after section heading
    \setaftersecskip{1.7ex}

    %% set name of bibliography to 'references'
    %%\renewcommand{\bibname}{\mdseries\Large\sffamily References}

    % % Title flush left
    \pretitle{\par\vskip 3em
      \begin{flushleft}\LARGE\sffamily\bfseries}
    \posttitle{\end{flushleft}\par\vskip 0.5em}
    \preauthor{\begin{flushleft}\Large}
    \postauthor{\end{flushleft}}
    \predate{\begin{flushleft}\normalsize}
    \postdate{\end{flushleft}}

    %% 'abstract' bigger skip from title
    %%\addto\captionsamerican{\renewcommand*{\abstractname}{}}
    \renewcommand{\abstractnamefont}{\normalfont\scriptsize}
    \renewcommand{\abstracttextfont}{\normalfont\scriptsize}
    \abstractrunin
  }
\chapterstyle{article-sans}
#+END_SRC

* SuperNEMO article style
:PROPERTIES:
:CUSTOM_ID: supernemo_article_style
:TANGLE: supernemo-article-style.sty
:END:

** Basics
#+BEGIN_SRC latex
  \NeedsTeXFormat{LaTeX2e}
  \ProvidesPackage{supernemo-article-style}[2013/07/03 v0.01 Bundling of SuperNEMO article items]
#+END_SRC

** Set fonts
#+BEGIN_SRC latex
  \RequirePackage{lmodern}
  \RequirePackage{mathpazo}
  \RequirePackage[scaled=.95]{helvet}
  \RequirePackage{courier}
#+END_SRC

** Graphics packages
#+BEGIN_SRC latex
  \RequirePackage{graphicx}
  \RequirePackage{wrapfig}
  \RequirePackage{tikz}
#+END_SRC

** Color
#+BEGIN_SRC latex
  %%\usepackage{color}
  \definecolor{gris25}{gray}{0.25}
  \definecolor{sncolor}{rgb}{0.0,0.0,0.0}
#+END_SRC

** Geometry
#+BEGIN_SRC latex
  \RequirePackage{a4wide}
  \linespread{1.02}
  \setlength{\textwidth}{15.5cm}
  \setlength{\textheight}{690pt}
  \setlength{\evensidemargin}{0cm}
  \addtolength{\voffset}{-0.5cm}
  \setlength{\headheight}{15pt}
#+END_SRC

** Authoring & bibliography
[[http://www.ctan.org/pkg/authblk][The package]] redefines the =\author= command to work as normal or to allow a
footnote style of author/affiliation input.
#+BEGIN_SRC latex
  \RequirePackage{authblk}
#+END_SRC

#+BEGIN_SRC latex
  \RequirePackage[nottoc,notlof,notlot]{tocbibind}
#+END_SRC

** Layout
#+BEGIN_SRC latex
  \RequirePackage{fancyhdr}
#+END_SRC

*** Logo
#+BEGIN_SRC latex
  \newcommand{\snlogo}{
    \resizebox{!}{35mm}{
      \begin{tikzpicture}[y=-1cm]
        \tikzstyle{line}=[line width=3.5pt, sncolor]

        \path[fill=white] (3.5,0.5) rectangle (16.5,13);
        \draw[line,cap=round,sncolor] (15.77099,10.87346) +(-146:5.28649) arc (-146:-94:5.28649);
        \draw[line,cap=round,sncolor] (14.21807,12.1247) +(-123:5.16183) arc (-123:-77:5.16183);
        \draw[line] (5.94556,9.46111) +(139:0.23466) arc (139:319:0.23466);
        \draw[line] (6.29889,9.15444) +(139:0.2332) arc (139:-41:0.2332);
        \draw[line] (6.65333,8.85017) +(139:0.23393) arc (139:319:0.23393);
        \draw[line] (7.00556,8.54222) +(139:0.23393) arc (139:-41:0.23393);
        \draw[line] (7.36,8.23796) +(140:0.23321) arc (140:319:0.23321);
        \draw[line] (7.71222,7.93) +(139:0.23466) arc (139:-41:0.23466);
        \draw[line] (8.06667,7.62462) +(140:0.23321) arc (140:319:0.23321);
        \draw[line] (5.94556,3.93889) +(-139:0.23466) arc (-139:-319:0.23466);
        \draw[line] (6.29889,4.24556) +(-139:0.2332) arc (-139:41:0.2332);
        \draw[line] (6.65333,4.54983) +(-139:0.23393) arc (-139:-319:0.23393);
        \draw[line] (7.00556,4.85778) +(-139:0.23393) arc (-139:41:0.23393);
        \draw[line] (7.36,5.16204) +(-140:0.23321) arc (-140:-319:0.23321);
        \draw[line] (7.71222,5.47) +(-139:0.23466) arc (-139:41:0.23466);
        \draw[line] (8.06667,5.77538) +(-140:0.23321) arc (-140:-319:0.23321);

        \draw[line] (4.66667,9.66667) -- (15.36667,9.66667);
        \draw[line] (4.66667,9.96667) -- (15.36667,9.96667);
        \draw[line] (4.66667,10.26667) -- (15.36667,10.26667);
        \draw[line] (4.66667,3.16667) -- (15.36667,3.16667);
        \draw[line] (4.66667,3.46667) -- (15.36667,3.46667);
        \draw[line] (4.66667,3.76667) -- (15.36667,3.76667);

        \path[draw=sncolor,line,fill=white] (9.98667,6.56222) circle (2cm);

        \draw[line,cap=round] (9.91952,6.72683) +(149:1.52587) arc (149:229:1.52587);
        \draw[line,cap=round] (9.96484,6.84433) +(-129:1.64987) arc (-129:-85:1.64987);
        \draw[line,cap=round] (10.20558,6.59684) +(55:1.8469) arc (55:151:1.8469);
        \draw[line,cap=round] (9.96256,6.58451) +(-85:1.39531) arc (-85:-33:1.39531);
        \draw[line,cap=round] (10.05707,6.51492) +(-35:1.28299) arc (-35:31:1.28299);
        \draw[line,cap=round] (10.09998,6.44356) +(35:1.28202) arc (35:97:1.28202);
        \draw[line,cap=round] (10.09126,6.72875) +(99:1.00595) arc (99:170:1.00595);
        \draw[line,cap=round] (10.03469,6.72368) +(169:0.95117) arc (169:237:0.95117);
        \draw[line,cap=round] (9.94585,6.58108) +(-124:0.77764) arc (-124:-44:0.77764);
        \draw[line,cap=round] (9.93399,6.50534) +(-41:0.72926) arc (-41:36:0.72926);
        \draw[line,cap=round] (10.03246,6.57945) +(35:0.60217) arc (35:126:0.60217);
        \draw[line,cap=round] (10.01821,6.63888) +(130:0.54491) arc (130:224:0.54491);
        \draw[line,cap=round] (9.91514,6.60478) +(-121:0.45168) arc (-121:-56:0.45168);
        \draw[line,cap=round] (10.00024,6.51523) +(-49:0.32865) arc (-49:43:0.32865);
        \draw[line,cap=round] (10.00457,6.53792) +(44:0.3094) arc (44:156:0.3094);
        \draw[line,cap=round] (9.85985,6.60767) +(162:0.13797) arc (162:337:0.13797);

        \fontfamily{phv}\fontseries{b}
        \fontsize{30.0}{36.0}\selectfont{}
        \path (10.1,11.8) node[text=sncolor,anchor=base] {c~o~l~l~a~b~o~r~a~t~i~o~n};
        \path (10,2.28889) node[text=sncolor,anchor=base] {s~~u~~p~~e~~r~~n~~e~~m~~o};

      \end{tikzpicture}%
    }
  }
#+END_SRC

*** Cover page
#+BEGIN_SRC latex
  \makeatletter
  \newcommand{\HRule}{\rule{\linewidth}{1mm}}
  \renewcommand*{\maketitle}{}
  \renewenvironment{abstract}{%
    \pagestyle{empty}
    \vspace*{\stretch{2}}
    \begin{flushright}
      \HRule
      \\[9mm]
        {
          \bf \Huge \@title
        }
        \\[15mm]
        \large

        \snlogo\hfill%
        %%\includegraphics[height=35mm]{supernemo_logo} \hfill%
        \parbox[b]{10cm}{\begin{flushright}
            \@author
        \end{flushright}}
        \\[5mm]
        \HRule
        \\[9mm]
    \end{flushright}
    \begin{center}
      \bf\large \abstractname
    \end{center}
    \begin{center}
      \begin{minipage}[b]{12cm}
        \small
  }%
  {%
      \end{minipage}
    \end{center}
    \vspace*{\stretch{2}}
    \begin{center}
      Document version 0.1\\
      %% Document revision \SVNrevision
    \end{center}
    %% \pagestyle{plain}
    \newpage
  }
  \makeatother
#+END_SRC

*** Footnote
#+BEGIN_SRC latex
  \renewcommand{\footnoterule}{\color{gris25}%
    \vskip-\footruleskip\vskip-\footrulewidth%
    \vspace{10pt}\hrule width\columnwidth height1.5pt \vspace{5pt} \color{gris25}}
  \renewcommand{\thefootnote}{\alph{footnote}}
  \interfootnotelinepenalty=10000
#+END_SRC

*** Caption
#+BEGIN_SRC latex
  \RequirePackage[margin=20pt,labelfont=bf,font=footnotesize,labelsep=endash]{caption}
#+END_SRC

* CV style
:PROPERTIES:
:CUSTOM_ID: cv_style
:TANGLE: cv_style.sty
:END:

A homemade style for producing nice looking vit\ae with =org-mode=. The main
trick is to use [[http://mirrors.linsrv.net/tex-archive/macros/latex/contrib/titlesec/][titlesec]] LaTeX package to tweak the
title/section/subsection... look and thus, use all the hierarchical view of
=org-mode=. Then the style itself is a mix of [[http://kjhealy.github.io/kjh-vita/][Kieran Healy's CV]] with an old one
I had.

** Basics
#+BEGIN_SRC latex
  \ProvidesPackage{cv_style}
#+END_SRC

** Default parameter values
These values can be overloaded within the org file using =#+LATEX_HEADER=
command.

#+BEGIN_SRC latex
  \def\myemail{xavier.garrido@lal.in2p3.fr}
  \def\myweb{}
  \def\myphone{+33 (0)1 64 46 84 28}
  \def\myfax{+33 (0)1 69 07 94 04}

  \definecolor{theMainColor}{HTML}{AA0000}
  \definecolor{theRefColor}{HTML}{000575}
#+END_SRC

** Packages
#+BEGIN_SRC latex
  \usepackage{titlesec}
  \usepackage{enumitem}
  \hypersetup{
    xetex,
    colorlinks=true,
    urlcolor=theRefColor,
    plainpages=false,
    pdfpagelabels,
    bookmarksnumbered,
    pagebackref
  }
  \setlength{\parindent}{0cm}
#+END_SRC

** Fonts
Choose fonts for use with xelatex. Minion and Myriad are widely available, from
Adobe. Inconsolata is used as monospace font.

#+BEGIN_SRC latex
  \setromanfont[Mapping={tex-text},Numbers={OldStyle},Ligatures={Common}]{Minion Pro}
  \setsansfont[Mapping=tex-text,Colour=theMainColor]{Myriad Pro}
  \setmonofont[Mapping=tex-text,Scale=0.9]{Inconsolata}
#+END_SRC

** Document title
#+BEGIN_SRC latex
  \renewcommand*{\maketitle}{%
    %%{\flushright\large\textsf{\@author}}\\
    \begin{minipage}[t]{2.95in}
      \flushright {\footnotesize \href{http://www.lal.in2p3.fr}{Laboratoire de l'Accélérateur Linéaire}
        \\ Building 200, \\ Paris XI University, \\ \vspace{-0.05in} 91898 Orsay Cedex}
    \end{minipage}
    \hfill
    \hfill
    \begin{minipage}[t]{1.7in}
      \flushright \footnotesize Phone:~\myphone \\
      Fax:~\myfax  \\
      {\scriptsize  \texttt{\href{mailto:\myemail}{\myemail}}} \\
      {\scriptsize  \texttt{\href{\myweb}{\myweb}}}
    \end{minipage}
  }
#+END_SRC

** Tweaking =\section=
=titlesec= format respects the following writing convention:
#+BEGIN_SRC latex :tangle no
  \titleformat{<command>}{<shape>}{<format>}{<label>}{<sep>}{<before-code>}{<after-code>}
#+END_SRC

*** =section=
#+BEGIN_SRC latex :tangle no
  \titleformat{\section} %command
              {\large\sf\raggedright} %format
              {} %label
              {0pt} %sep
              {} %before
              [] %after
  \titlespacing{\section}{0pt}{10pt}{5pt}
#+END_SRC

#+BEGIN_SRC latex
  \titleformat{\section} %command
              [leftmargin] %shape
              {\footnotesize\sf\raggedleft} %format
              {} %label
              {0pt} %sep
              {\lowercase} %before
              [] %after
  \titlespacing{\section}{90pt}{5pt}{15pt}
#+END_SRC

*** =subsection=
#+BEGIN_SRC latex
  \titleformat{\subsection} %command
              {\normalsize\it} %format
              {} %label
              {0pt} %sep
              {} %before
              [] %after
  \titlespacing{\subsection}{0pt}{-5mm}{0pt}
#+END_SRC

*** =itemize=
#+BEGIN_SRC latex
  \renewenvironment{itemize}{
    \begin{list}{\textbullet}{%
        \setlength{\itemsep}{0.05in}
        \setlength{\parsep}{0in}
        \setlength{\parskip}{0in}
        \setlength{\topsep}{0in}
        \setlength{\partopsep}{0in}
        \setlength{\leftmargin}{0.1in}}
      \vspace{-5mm}}{\end{list}}
%%  \renewenvironment{enumerate}{
%%    \begin{list}{}{%
%%        \setlength{\itemsep}{0.05in}
%%        \setlength{\parsep}{0in}
%%        \setlength{\parskip}{0in}
%%        \setlength{\topsep}{0in}
%%        \setlength{\partopsep}{0in}
%%        \setlength{\leftmargin}{0.1in}}}{\end{list}}
#+END_SRC

* KOMA/LaTeX letter styles
:PROPERTIES:
:CUSTOM_ID: koma_letter
:END:

This part holds some LaTeX styles for cover letter. This is mainly inspired by
this [[http://stefano.italians.nl/archives/55][tutorial]]. First, the basics are defined namely the layout of the cover
letter. Then /personal data/ informations are set given the usecase
(french/english).

** Cover letter layout
*** Packages
#+NAME: kpackages
#+BEGIN_SRC latex :results none :tangle no
  \usepackage{fontspec}
  \usepackage{xltxtra}
  \usepackage{marvosym}
  \usepackage{graphicx}
  \usepackage[dvipdfm]{geometry}
  \usepackage{pst-barcode}
#+END_SRC
*** Fonts
#+NAME: kfonts
#+BEGIN_SRC latex :results none :tangle no
  \setmainfont{GaramondNo8}
#+END_SRC
*** Lengths
#+NAME: klengths
#+BEGIN_SRC latex :results none :tangle no
  \@setplength{firstheadvpos}{0pt}%
  \@setplength{firstheadwidth}{\paperwidth}%
  \@setplength{firstfootvpos}{\paperheight}%
  \@addtoplength[-]{firstfootvpos}{\useplength{toaddrvpos}}%
  \@addtoplength{refvpos}{-1.5\baselineskip}%
  \@newplength{infocolwidth}%
  % Kohm & Morawski 2005, C.7. Modifikationen (Modifications)
  \ifdim \textwidth<0.666\paperwidth
   \@setplength{infocolwidth}{.22222\paperwidth}%
  \else
   \@setplength{infocolwidth}{0.1667\paperwidth}%
   \fi
#+END_SRC

*** Page body
Shift the page body on the left to make room for personal data and logo.
#+NAME: kbody
#+BEGIN_SRC latex :results none :tangle no
  \setlength{\parindent}{0cm}
  \setlength{\oddsidemargin}{\useplength{toaddrhpos}}%
  \addtolength{\oddsidemargin}{-1in}%
  % Take care that the shift stays intact even after recalculating the page
  % layout (see Kohm & Morawski 2005, section C.7)
  \l@addto@macro{\@typearea@end}{%
    \setlength{\oddsidemargin}{\useplength{toaddrhpos}}%
   \addtolength{\oddsidemargin}{-1in}%
  }
#+END_SRC

*** Fancy header
#+NAME: kheader
#+BEGIN_SRC latex :results none :tangle no
  \firsthead{%
   \fontsize{8}{9}\sffamily
   \hspace*{\fill}%
   \begin{picture}(0,0)%
   \put(0,0){\parbox[t]{\useplength{infocolwidth}}{%
   \vspace{\useplength{toaddrvpos}}%
   \usekomavar{fromlogo}%
   }%
   }%
   \put(0,0){\parbox[t]{\useplength{infocolwidth}}{%
   \raggedright
   \vspace{\useplength{refvpos}}%
   \vspace{\useplength{refaftervskip}}%
   \usekomavar{place}\usekomavar{placeseparator}\\
   \usekomavar{date}\\[10\baselineskip]
   \usekomavar{fromname}\\
   \usekomavar{fromaddress}\\
   [\baselineskip]
   \Telefon~\usekomavar{fromphone}\\
   \Letter~\usekomavar{fromemail}
   }%
  }%
   \end{picture}%
   \hspace*{\useplength{infocolwidth}}%
  }%

  % avoid the display of the date in the default position
  \l@addto@macro\@firstheadfootfield{\setkomavar{date}{}}
#+END_SRC

*** Full layout
#+NAME: klayout
#+BEGIN_SRC latex :results none :tangle no
  <<kpackages>>
  <<kfonts>>
  <<klengths>>
  <<kbody>>
  <<kheader>>
#+END_SRC

** Personal data
*** English
:PROPERTIES:
:TANGLE: english.lco
:END:

#+BEGIN_SRC latex
  \ProvidesFile{english.lco}[]
  \usepackage[english]{babel}
#+END_SRC

#+BEGIN_SRC latex :noweb yes
  <<klayout>>
#+END_SRC

#+BEGIN_SRC latex
  \setkomavar{fromname}{Xavier Garrido}
  \setkomavar{fromaddress}{Laboratoire de l'Accélérateur Linéaire\\Centre Scientifique d'Orsay\\91898 Orsay Cedex}
  \setkomavar{fromemail}{garrido@lal.in2p3.fr}
  \setkomavar{fromphone}{+33 1 64 46 84 28}
  \setkomavar{fromfax}{}
  \setkomavar{fromurl}{}
  %%\setkomavar{fromlogo}{\includegraphics[width=3cm]{logo_upsud_bw}}
  \setkomavar{place}{Orsay}
  \setkomavar{signature}{Xavier Garrido\\Assistant professor at University Paris-Sud}
#+END_SRC

#+BEGIN_SRC latex
  \endinput
#+END_SRC

*** French
:PROPERTIES:
:TANGLE: french.lco
:END:

#+BEGIN_SRC latex
  \ProvidesFile{french.lco}[]
  \usepackage[frenchb]{babel}
#+END_SRC

#+BEGIN_SRC latex :noweb yes
  <<klayout>>
#+END_SRC

#+BEGIN_SRC latex
  \setkomavar{fromname}{Xavier Garrido}
  \setkomavar{fromaddress}{Laboratoire de l'Accélérateur Linéaire\\Centre Scientifique d'Orsay\\91898 Orsay Cedex}
  \setkomavar{fromemail}{garrido@lal.in2p3.fr}
  \setkomavar{fromphone}{+33 1 64 46 84 28}
  \setkomavar{fromfax}{}
  \setkomavar{fromurl}{}
  %%\setkomavar{fromlogo}{\includegraphics[width=3cm]{logo_upsud_bw}}
  \setkomavar{place}{Orsay}
  \setkomavar{signature}{Xavier Garrido\\Maître de Conférence à l'Université Paris-Sud}
#+END_SRC

#+BEGIN_SRC latex
  \endinput
#+END_SRC

* Beamer styles
** Special progress bar in footline
#+NAME: line
#+HEADERS: :var color="gray"
#+BEGIN_SRC sh :results output :tangle no
  echo '  \color{'$color'}% to color the progressbar'
  echo '  \hspace*{-\beamer@leftmargin}%'
  echo '  \rule{\beamer@leftmargin}{2pt}%'
  echo '  \rlap{\rule{\dimexpr'
  echo '      \beamer@startpageofframe\dimexpr'
  echo '      \beamer@rightmargin+\textwidth\relax/\beamer@endpageofdocument}{1pt}}'
  echo '  % next empty line is mandatory!'
  echo ' '
  echo '  \vspace{.0\baselineskip}'
  echo '         {}'
#+END_SRC

#+NAME: footline
#+HEADERS: :var style="default" :var color="gray"
#+BEGIN_SRC sh :results output :tangle no :noweb yes
  echo '\defbeamertemplate{footline}{cbfootline}{%'
  if [ "${style}" == "ddpfo" ]; then
      echo '  \usebeamerfont{page number in head/foot}'
      echo '  \hspace{1em}\insertshortdate\,-\,\insertshortauthor\hfill'
      echo '  \insertpagenumber\,/\,\insertpresentationendpage'
      echo '  \kern1em\vskip-1pt'
      <<line>>
  elif [ "${style}" == "snemo" ]; then
      echo ''
  elif [ "${style}" == "cpp_teaching" ]; then
      echo '  \usebeamerfont{page number in head/foot}'
      echo '  \hspace{1em}\inserttitle\hfill'
      echo '  \insertpagenumber'
      echo '  \kern1em\vskip2pt'
      <<line>>
  fi
  echo '}'
#+END_SRC
** Template
:PROPERTIES:
:CUSTOM_ID: custom_beamer
:TANGLE:    custom-beamer.sty
:END:
*** Basics
#+BEGIN_SRC latex
  \NeedsTeXFormat{LaTeX2e}
  \ProvidesPackage{custom-beamer}[2013/09/03 v0.01 Custom beamer templates]
#+END_SRC
*** Package options
#+BEGIN_SRC latex
  \RequirePackage{kvoptions}
  \SetupKeyvalOptions{
     family=cb,
     prefix=cb@
   }
   \DeclareBoolOption[false]{nologo}
   \DeclareBoolOption[false]{notitlelogo}
   \DeclareBoolOption[false]{noheaderlogo}
   \DeclareBoolOption[false]{ddpfo}
   \DeclareBoolOption[false]{snemo}
   \DeclareBoolOption[false]{cpp_teaching}
   \ProcessKeyvalOptions*
#+END_SRC
**** General options
#+BEGIN_SRC latex
  \RequirePackage{ifthen}
  \ifthenelse{\boolean{cb@nologo}}{
    \setboolean{cb@notitlelogo}{true}
    \setboolean{cb@noheaderlogo}{true}
  }{}
  \newboolean{has_driver_name}
  \setboolean{has_driver_name}{false}
#+END_SRC
*** Default themes
#+BEGIN_SRC latex
  \usetheme{default}
  \usecolortheme{whale}
#+END_SRC
*** Color definitions
Given the =driver= to be used, generic colors are set to the most common part of
a beamer presentation.

**** D2PFO colors
#+BEGIN_SRC latex
  \ifthenelse{\boolean{cb@ddpfo}}{
    \setboolean{has_driver_name}{true}
    \definecolor{red}{RGB}{221,42,43}
    \definecolor{green}{RGB}{132,184,24}
    \definecolor{blue}{RGB}{0,72,112}
    \definecolor{gray}{RGB}{107,108,110}

    \colorlet{generic0}{green}
    \colorlet{generic1}{green}
    \colorlet{generic2}{blue}
    \colorlet{generic3}{gray}
  }{}
#+END_SRC

**** SuperNEMO colors
#+BEGIN_SRC latex
  \ifthenelse{\boolean{cb@snemo}}{
    \setboolean{has_driver_name}{true}
    \definecolor{red}{RGB}{221,42,43}
    \definecolor{green}{RGB}{132,184,24}
    \definecolor{blue}{RGB}{60,72,112}
    \definecolor{gray}{RGB}{107,108,110}

    \colorlet{generic0}{green}
    \colorlet{generic1}{green}
    \colorlet{generic2}{blue}
    \colorlet{generic3}{gray}
  }{}
#+END_SRC
**** C++ teaching colors
#+BEGIN_SRC latex
  \ifthenelse{\boolean{cb@cpp_teaching}}{
    \setboolean{has_driver_name}{true}
    \definecolor{red}{RGB}{221,42,43}
    \definecolor{green}{RGB}{132,184,24}
    \definecolor{blue}{RGB}{0,72,112}
    \definecolor{gray}{RGB}{107,108,110}

    \colorlet{generic0}{green}
    \colorlet{generic1}{green}
    \colorlet{generic2}{blue}
    \colorlet{generic3}{gray}
  }{}
#+END_SRC

Finally apply the color settings to beamer elements:
#+BEGIN_SRC latex
  \ifthenelse{\boolean{has_driver_name}}{
    \setbeamercolor{structure}{fg=generic2}
    \setbeamercolor{alerted text}{fg=generic0}
    \setbeamercolor{example text}{fg=generic1}
    \setbeamercolor{block title}{use=structure,fg=structure.bg, bg=structure.fg}
    \setbeamercolor{block body}{use=structure, fg=structure.fg, bg=structure.bg}
    \setbeamercolor{frametitle}{use=structure, fg=structure.fg, bg=}
    \setbeamercolor{example title}{use=example,fg=example.bg, bg=example.fg}
    \setbeamercolor{example body}{use=example, fg=example.fg, bg=example.bg}
    \setbeamercolor{itemize item}{fg=generic2}

    \setbeamercolor{ruc_upper}{fg=white,bg=red}
    \setbeamercolor{ruc_lower}{fg=red,bg=white}
    \setbeamercolor{guc_upper}{fg=white,bg=green}
    \setbeamercolor{guc_lower}{fg=green,bg=white}
    \setbeamercolor{buc_upper}{fg=white,bg=blue}
    \setbeamercolor{buc_lower}{fg=blue,bg=white}

    \setbeamercolor{lruc}{fg=white,bg=red!10}
    \setbeamercolor{lrtuc}{fg=red,bg=red!10}
    \setbeamercolor{lguc}{fg=white,bg=green!10}
    \setbeamercolor{lgtuc}{fg=green,bg=green!10}
    \setbeamercolor{lbuc}{fg=white,bg=blue!10}
    \setbeamercolor{lbtuc}{fg=blue,bg=blue!10}
  }{
    %%\PackageWarning{custom-beamer}{You must specify a 'driver' name !}{You must specify a know 'driver' name}}{
  }
#+END_SRC
*** Beamer options
#+BEGIN_SRC latex
  \DeclareOptionBeamer{shadow}[true]{\def\beamer@themerounded@shadow{#1}}
  \ExecuteOptionsBeamer{shadow=true}
  \ProcessOptionsBeamer

  \setbeamercovered{transparent}
  \setbeamertemplate{blocks}[rounded][shadow=\beamer@themerounded@shadow]
#+END_SRC
*** Title page definition
First, make title frame plain (no page number, not footline...)
#+BEGIN_SRC latex
  \def\maketitle{\ifbeamer@inframe\titlepage\else\frame[plain,noframenumbering]{\titlepage}\fi}
#+END_SRC

Also add a logo of the University of Paris South
#+BEGIN_SRC latex
  \ifthenelse{\boolean{cb@notitlelogo}}{}{
    \titlegraphic{\includegraphics[scale=0.2]{logo_upsud}}}
#+END_SRC

Then define the custom beamer template
#+BEGIN_SRC latex
  \defbeamertemplate*{title page}{custom}[1][colsep=-4bp,
    rounded=true,shadow=\beamer@themerounded@shadow]{
    \vbox{}
    \vfill
    \begin{centering}
      \begin{beamercolorbox}[sep=8pt,center,#1]{title}
        \usebeamerfont{title}\insertprefixtitle\inserttitle\par%
        \ifx\insertsubtitle\@empty%
        \else%
        \vskip0.25em%
               {\usebeamerfont{subtitle}\usebeamercolor[fg]{subtitle}\insertsubtitle\par}%
               \fi%
      \end{beamercolorbox}%
      \vskip1em\par
      %%\begin{beamercolorbox}[sep=8pt,center,#1]{author}
      %%  \usebeamerfont{author}\insertauthor
      %%\end{beamercolorbox}
      %%\begin{beamercolorbox}[sep=8pt,center,#1]{institute}
      %%  \usebeamerfont{institute}\insertinstitute
      %%\end{beamercolorbox}
      %%\begin{beamercolorbox}[sep=8pt,center,#1]{date}
      %%  \usebeamerfont{date}\insertdate
      %%\end{beamercolorbox}
      \vskip0.5em{\usebeamercolor[fg]{titlegraphic}\inserttitlegraphic\par}
    \end{centering}
    \vfill
  }
#+END_SRC

**** Insert prefix to title
#+BEGIN_SRC latex
  \newcommand{\insertprefixtitle}{}
  \ifthenelse{\boolean{cb@cpp_teaching}}{
    \newcommand{\Cpp}{\mbox{C\vspace{.5em}\protect\raisebox{.2ex}{\footnotesize++~}}}
    \renewcommand{\insertprefixtitle}{\textbf{Cours \Cpp}\vskip0.25em\usebeamerfont{subtitle}}
  }{}
#+END_SRC
*** Part page definition
This tweak is used to include =appendix= page with the name style as =title=
page. First, rename the =appendix= name :
#+BEGIN_SRC latex
  \renewcommand{\appendixname}{Annexes}
#+END_SRC

Then use almost the default part page style but include the command =\appendi=
in order to keep the total page number unchanged.
#+BEGIN_SRC latex
  \defbeamertemplate*{part page}{custom}[1][colsep=-4bp,
    rounded=true,shadow=\beamer@themerounded@shadow]
                     {
                       \appendix
                       \begin{centering}
                         \vskip1em\par
                         \begin{beamercolorbox}[sep=16pt,center,#1]{part title}
                           \usebeamerfont{part title}\insertpart\par
                         \end{beamercolorbox}
                       \end{centering}
                     }

#+END_SRC
*** Adding logo to frametitle
#+BEGIN_SRC latex
  \ifthenelse{\boolean{cb@noheaderlogo}}{}{
    \RequirePackage[absolute,overlay]{textpos}
    \addtobeamertemplate{frametitle}{}{%
      \begin{textblock}{14}(13.5,0.25)
        \includegraphics[height=1.2cm]{logo_upsud}
    \end{textblock}}}
#+END_SRC
*** Colored block environment
#+BEGIN_SRC latex
  \RequirePackage{xparse}
  \NewDocumentEnvironment{cbox}{O{0.9\linewidth} O{lbtuc} O{\centering} D(){}}
                 {\begin{center}
                     \begin{minipage}[c]{#1}
                       \begin{beamerboxesrounded}[upper=#2,lower=#2,shadow=false]
                         {#4}
                         #3
                 }
                 {
                       \end{beamerboxesrounded}
                     \end{minipage}
                   \end{center}
                 }
#+END_SRC
*** Footline
Remove navigation symbols
#+BEGIN_SRC latex
  \beamertemplatenavigationsymbolsempty
#+END_SRC

Add special footline with a slick progress bar
#+BEGIN_SRC latex :noweb yes
  \ifthenelse{\boolean{has_driver_name}}{
    \ifthenelse{\boolean{cb@ddpfo}}{
      <<footline(style="ddpfo", color="generic3")>>
    }{}
    \ifthenelse{\boolean{cb@snemo}}{
      <<footline(style="snemo", color="generic3")>>
    }{}
    \ifthenelse{\boolean{cb@cpp_teaching}}{
      <<footline(style="cpp_teaching", color="generic3")>>
    }{}
    \setbeamertemplate{footline}[cbfootline]{}
    \setbeamercolor{footline}{use=structure, fg=generic3, bg=structure.bg}
  }{}
#+END_SRC

* Exporting styles
:PROPERTIES:
:CUSTOM_ID: export_styles
:TANGLE: latex-templates.sh
:END:

Given the generation of LaTeX styles from the previous items, the files are
exported to =$TEXMFHOME= to make them available from everywhere.

** List of files to export
#+TBLNAME: style_files
| $TEXMFHOME/tex/latex/commonstuff                 | org-preamble.sty            |
| $TEXMFHOME/tex/latex/commonstuff                 | memoir-article-style.sty    |
| $TEXMFHOME/tex/latex/commonstuff                 | supernemo-article-style.sty |
| $TEXMFHOME/tex/latex/commonstuff                 | cv_style.sty                |
| $TEXMFHOME/tex/latex/commonstuff/koma-letter-lco | english.lco                 |
| $TEXMFHOME/tex/latex/commonstuff/koma-letter-lco | french.lco                  |
| $TEXMFHOME/tex/latex/commonstuff                 | custom-beamer.sty           |

** Script to do the export
#+NAME: export_script(dirs=style_files[,0], files=style_files[,1])
#+BEGIN_SRC sh :shebang #!/bin/bash
  if [ ! -d $TEXMFHOME ]; then
      echo "ERROR: No TEXMFHOME installation !"
      return 1
  fi

  mode="install"

  if [ "$1" == "clean" ]; then
      mode="clean"
  fi

  ff=( $files )
  dd=( $dirs )

  for i in ${!ff[*]}
  do
      a_dir=$(eval echo ${dd[$i]})
      a_file=${ff[$i]}
      if [ $mode = install ]; then
          echo "NOTICE: Installing ${a_file} into ${a_dir}"
          if [ ! -d ${a_dir} ]; then
              echo "NOTICE: Creating directory ${a_dir}"
              mkdir -p ${a_dir}
          fi
          cp ${a_file} ${a_dir}
      elif [ $mode = clean ]; then
          echo "NOTICE: Removing ${a_file} from ${a_dir}"
          rm -f ${a_dir}/${a_file}
      fi
  done
#+END_SRC
